util.log("\n□□□□□□□□□□□□□■□□□□□■□□□□□□□□□■□□□□□□□□□□□□□■□□□\n□■■■■■■■■■■□□□■□□□□■□□□□□□□□□□■□□□□□□■■■□□□■□□□\n□■□□□■□□□□□□■■■■□■■■■■■□□□■■■■■■■■■□□□□□□□□■□□□\n□■□■■■■■■■□□□□□■□■□■□□■□□□■□□□□□□□■□□□□□□□■■■■■\n□■□■□□□□□■□□□□■□□■□■□□■□□□■□□□□□□□■□■■■■■□□■□□■\n□■□■■■■■■■□□□□■■□■■■■■■□□□■■■■■■■■■□□□■□□□□■□□■\n□■□■□□□□□■□□□■■□■■□■□□■□□□■□□□□□□□□□□■□□□□□■□□■\n□■□■■■■■■■□□■□■□□■□■□□■□□□■■■■■■■■■□□■□■□□□■□□■\n□■□□□□■□□□□□□□■□□■■■■■■□□□■■□□□□□□■□■□□□■□□■□□■\n□■□□■□■□■□□□□□■□□■□■□□■□□■□■□□□□□□■□■■■■■□□■□□■\n□■□■□□■□□■□□□□■□□□□■□□□□□■□■■■■■■■■□□□□□□□■□□□■\n■□■□□■■□□□■□□□■□□□□■□□□□■□□■□□□□□□■□□□□□□■□□■■□")


util.toast("你这个原批" .. players.get_name(players.user()) .. "纯纯的米孝子")
YUANSHEN1 = menu.list(YUANSHEN, "原神", {""}, "！！！")
menu.divider(YUANSHEN1, "妈的，忍不了，一秒把原神打开！他钟离的雷神", {}, "")
menu.divider(YUANSHEN1, "的温迪的纳西妲的刻晴的凝光的行秋的重云的香", {}, "")
menu.divider(YUANSHEN1, "菱的胡桃的甘雨的可莉的万叶的凌华的凌人的早", {}, "")
menu.divider(YUANSHEN1, "柚的优菈的迪卢克的阿贝多的班尼特的宵宫的莫", {}, "")
menu.divider(YUANSHEN1, "娜的申鹤的璃月的蒙德的稻妻的须弥的至冬的原", {}, "")
menu.divider(YUANSHEN1, "神的都是我的嗯啊，原原原！！好好玩原原原原", {}, "")
menu.divider(YUANSHEN1, "原原原蹦蹦炸弹！拒收病婿！天理尝蛆！靖妖傩", {}, "")
menu.divider(YUANSHEN1, "舞！烧冻鸡翅！斩尽牛杂！这是斩灭海参的力量", {}, "")
menu.divider(YUANSHEN1, "这是忘放孜然！神里流霜灭！别想投胎哦！裁雨", {}, "")
menu.divider(YUANSHEN1, "留虹！无想的一刀！大原特原！大原特原！", {}, "")

menu.divider(YUANSHEN, "原神! 启动!")
menu.hyperlink(YUANSHEN, "下载崩坏学院2", "https://www.benghuai.com/")
menu.hyperlink(YUANSHEN, "下载崩坏3", "https://www.bh3.com/")
menu.hyperlink(YUANSHEN, "下载未定事件簿", "https://wd.mihoyo.com/")
menu.hyperlink(YUANSHEN, "下载原神", "https://ys.mihoyo.com/")
menu.hyperlink(YUANSHEN, "下载Genshin", "https://genshin.hoyoverse.com/en")
menu.hyperlink(YUANSHEN, "下载崩坏：星穹铁道", "https://sr.mihoyo.com/")
menu.hyperlink(YUANSHEN, "下载绝区零", "https://zzz.mihoyo.com/")
menu.hyperlink(YUANSHEN, "打开米哈游", "https://www.mihoyo.com/")
