function character_action()
    menu.action(anims_root, "停止所有动画", {"sexstopanims"}, "", function(on_click)
        TASK.CLEAR_PED_TASKS_IMMEDIATELY(PLAYER.PLAYER_PED_ID())
    end)
    
    menu.divider(anims_root,"动作列表")

    special_actions = menu.list(anims_root, "特殊动画", {}, "")
    
    menu.action(special_actions, "握手", {}, "", function(on_click)
        play_anim("mp_ped_interaction","handshake_guy_a", -1)
    end)   
    menu.action(special_actions, "酒吧前台", {}, "", function(on_click)
        play_anim("anim@amb@clubhouse@bar@drink@idle_a","idle_a_bartender", -1)
    end)
    menu.action(special_actions, "酒吧前台", {}, "", function(on_click)
        play_anim("anim@amb@clubhouse@bar@drink@idle_a","idle_a_bartender", -1)
    end)



    menu.action(special_actions, "酒吧前台", {}, "", function(on_click)
        play_anim("anim@amb@clubhouse@bar@drink@idle_a","idle_a_bartender", -1)
    end)
    menu.action(special_actions, "整理", {}, "", function(on_click)
        play_anim("missmic4","michael_tux_fidget", -1)
    end)
    menu.action(special_actions, "握手3", {}, "", function(on_click)
        play_anim("mp_ped_interaction","handshake_guy_a", -1)
    end)
    menu.action(special_actions, "握手4", {}, "", function(on_click)
        play_anim("mp_ped_interaction","handshake_guy_a", -1)
    end)
    menu.action(special_actions, "握手5", {}, "", function(on_click)
        play_anim("mp_ped_interaction","handshake_guy_a", -1)
    end)








    anims_nroot = menu.list(anims_root, "自我动作", {}, "")
        menu.action(anims_nroot, "打管子", {}, "", function(on_click)
            play_anim("switch@trevor@jerking_off", "trev_jerking_off_loop", -1)
        end)
        menu.action(anims_nroot, "后入", {}, "", function(on_click)
            play_anim("rcmpaparazzo_2", "shag_loop_a", -1)
        end)
        menu.action(anims_nroot, "被后入", {}, "", function(on_click)
            play_anim("rcmpaparazzo_2", "shag_loop_poppy", -1)
        end)
        menu.action(anims_nroot, "摁头口", {}, "", function(on_click)
            play_anim("mini@prostitutes@sexlow_veh", "low_car_bj_loop_player", -1)
        end)
        menu.action(anims_nroot, "跪着口", {}, "", function(on_click)
            play_anim("mini@prostitutes@sexlow_veh", "low_car_bj_loop_female", -1)
        end)
        menu.action(anims_nroot, "摸头口", {}, "", function(on_click)
            play_anim("mini@prostitutes@sexlow_veh", "low_car_sex_loop_player", -1)
        end)
        menu.action(anims_nroot, "坐着抽插", {}, "", function(on_click)
            play_anim("mini@prostitutes@sexlow_veh", "low_car_sex_loop_female", -1)
        end)
    dances_root = menu.list(anims_root, "膝上舞蹈", {}, "")
        menu.action(dances_root, "拉普丹斯1", {}, "", function(on_click)
            play_anim("mini@strip_club@private_dance@part1", "priv_dance_p1", -1)
        end)
        menu.action(dances_root, "拉普丹斯2", {}, "", function(on_click)
            play_anim("mini@strip_club@private_dance@part2", "priv_dance_p2", -1)
        end)
        menu.action(dances_root, "拉普丹斯3", {}, "", function(on_click)
            play_anim("mini@strip_club@private_dance@part3", "priv_dance_p3", -1)
        end)
    gangguanwu = menu.list(anims_root, "钢管舞", {}, "")
        menu.action(gangguanwu, "钢管舞1", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_a_2_stage", "pole_a_2_stage", -1)
        end)
        menu.action(gangguanwu, "钢管舞2", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_b_2_stage", "pole_b_2_stage", -1)
        end)
        menu.action(gangguanwu, "钢管舞3", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_c_2_prvd_a", "pole_c_2_prvd_a", -1)
        end)
        menu.action(gangguanwu, "钢管舞4", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_c_2_prvd_b", "pole_c_2_prvd_b", -1)
        end)
        menu.action(gangguanwu, "钢管舞5", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_c_2_prvd_c", "pole_c_2_prvd_c", -1)
        end)
        menu.action(gangguanwu, "钢管舞6", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_c_2_stage", "pole_c_2_stage", -1)
        end)
        menu.action(gangguanwu, "钢管舞7", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_dance1", "pd_dance_01", -1)
        end)
        menu.action(gangguanwu, "钢管舞8", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_dance2", "pd_dance_02", -1)
        end)
        menu.action(gangguanwu, "钢管舞9", {}, "", function(on_click)
            play_anim("mini@strip_club@pole_dance@pole_dance3", "pd_dance_03", -1)
        end)
end