menu.trigger_commands("timeos off")--====时间显示
menu.trigger_commands("scriptname on")--===脚本名称
menu.trigger_commands("ridicule on")--====嘲讽2.0开启
menu.trigger_commands("chaofeng on")--====嘲讽开启
menu.trigger_commands("hostqu on")--===主机序列
menu.trigger_commands("proof on")--====火烧
menu.trigger_commands("wasd off")--====按键显示
menu.trigger_commands("speedmeteor on")--====时速表
menu.trigger_commands("openit on")--====自动节流开启
menu.trigger_commands("loadweapon on")--===自动加载保存过的武器
menu.trigger_commands("Richman on")--======赞助人员
menu.trigger_commands("stpv2 on")--=====丝滑传送2.0默认开启（更平滑）
menu.trigger_commands("anticage off")--=====启用笼子拦截（再也不会被笼子限制了--推荐on）
menu.trigger_commands("cantgod on")--=====谁瞄准你就关谁无敌！！！
menu.trigger_commands("Xiproplayer on")--=====自动开启移除XiPro玩家
menu.trigger_commands("SUPERMAN off")--一键超人--推荐on
menu.trigger_commands("huazhiupup off")--画质提升
menu.trigger_commands("GPS on")--GPS
--====on是开启off是关闭，自行修改·······