local cqcq_root = menu.attach_before(menu.ref_by_path('Stand>Console'),menu.list(menu.shadow_root(), '从前从前最终版', {"CqCqLuaScript"}, '', 
function()end))
menu.trigger_commands("CqCqLuaScript")
festive_div = menu.divider(cqcq_root, "*运行CqCqscript*", {}, "")
self = menu.list(cqcq_root, "自我选项", {}, "想要白嫖吗？？那就点进来吧！！") 
online = menu.list(cqcq_root, "在线选项", {}, "在线功能选项") 
vehicle = menu.list(cqcq_root, "载具选项", {}, "载具功能选项")
all = menu.list(cqcq_root, "全局选项", {}, "全局功能选项") 
chuansong = menu.list(cqcq_root, "传送选项", {}, "传送功能选项")
world = menu.list(cqcq_root, "世界选项", {}, "世界功能选项")
funfeatures = menu.list(cqcq_root, "娱乐选项", {}, "娱乐功能")
mod111 = menu.list(cqcq_root, "模组选项", {}, "刷一些模组")
renwuxx = menu.list(cqcq_root, "任务选项", {}, "任务专属")
constructorscript00 = menu.list(cqcq_root, "人物模型", {}, "模型功能选项")
Undefined = menu.list(cqcq_root, "第二菜单", {}, "加载CqCqscript2.0", function(); end) 
Fight_script = menu.list(cqcq_root, "战斗菜单", {}, "加载CqCqscript3.0", function(); end) 
qita = menu.list(cqcq_root, "其他选项", {}, "其他")
zalei = menu.list(cqcq_root, "问答选项", {}, "杂类")