--请注意，本地Ped获取的方式，经测试现在无法通过自定义的玩家接口实现
--如果一个本地Ped的功能，你需要换成player.user()，而不是pid或者你自定义的玩家获取缀
--某些不需要应用的本机数值现在被强制要求应用，而这些数值大多数没有标明作用
--我们根据GTVIP中对应的本机报错信息，新建了一个本机功能脚本
--我们将其中的本机不必要的数值，比如什么p1，p2这些未被标记但现在被强制应用的数值舍去
--大多数的功能，并不需要什么p1或者p2，舍去了不会对功能造成影响，反而能正常运行
--此本机库是修复GTVIP报错过程中发现的一些本机
--使用某些本机创建的function，现在已经不能自定义参数缀，大多数是因为强制应用参数导致

REQUEST_WEAPON_ASSET=--[[void]] function(--[[Hash (int)]] weaponHash)native_invoker.begin_call()native_invoker.push_arg_int(weaponHash)native_invoker.end_call_2(0x5443438F033E29C3)end
END_TEXT_COMMAND_DISPLAY_TEXT=--[[void]] function(--[[float]] x,--[[float]] y)native_invoker.begin_call()native_invoker.push_arg_float(x)native_invoker.push_arg_float(y)native_invoker.end_call_2(0xCD015E5BB0D96A57)end
ATTACH_ENTITY_TO_ENTITY=--[[void]] function(--[[Entity (int)]] entity1,--[[Entity (int)]] entity2,--[[int]] boneIndex,--[[float]] xPos,--[[float]] yPos,--[[float]] zPos,--[[float]] xRot,--[[float]] yRot,--[[float]] zRot,--[[BOOL (bool)]] p9,--[[BOOL (bool)]] useSoftPinning,--[[BOOL (bool)]] collision,--[[BOOL (bool)]] isPed,--[[int]] vertexIndex,--[[BOOL (bool)]] fixedRot)native_invoker.begin_call()native_invoker.push_arg_int(entity1)native_invoker.push_arg_int(entity2)native_invoker.push_arg_int(boneIndex)native_invoker.push_arg_float(xPos)native_invoker.push_arg_float(yPos)native_invoker.push_arg_float(zPos)native_invoker.push_arg_float(xRot)native_invoker.push_arg_float(yRot)native_invoker.push_arg_float(zRot)native_invoker.push_arg_bool(p9)native_invoker.push_arg_bool(useSoftPinning)native_invoker.push_arg_bool(collision)native_invoker.push_arg_bool(isPed)native_invoker.push_arg_int(vertexIndex)native_invoker.push_arg_bool(fixedRot)native_invoker.end_call_2(0x6B9BBD38AB0796DF)end
REMOVE_PARTICLE_FX=--[[void]] function(--[[int]] ptfxHandle,--[[BOOL (bool)]] p1)native_invoker.begin_call()native_invoker.push_arg_int(ptfxHandle)native_invoker.push_arg_bool(p1)native_invoker.end_call_2(0xC401503DFE8D53CF)end
START_NETWORKED_PARTICLE_FX_LOOPED_ON_ENTITY_BONE=--[[int]] function(--[[string]] effectName,--[[Entity (int)]] entity,--[[float]] xOffset,--[[float]] yOffset,--[[float]] zOffset,--[[float]] xRot,--[[float]] yRot,--[[float]] zRot,--[[int]] boneIndex,--[[float]] scale,--[[BOOL (bool)]] xAxis,--[[BOOL (bool)]] yAxis,--[[BOOL (bool)]] zAxis,--[[float]] r,--[[float]] g,--[[float]] b,--[[float]] a)native_invoker.begin_call()native_invoker.push_arg_string(effectName)native_invoker.push_arg_int(entity)native_invoker.push_arg_float(xOffset)native_invoker.push_arg_float(yOffset)native_invoker.push_arg_float(zOffset)native_invoker.push_arg_float(xRot)native_invoker.push_arg_float(yRot)native_invoker.push_arg_float(zRot)native_invoker.push_arg_int(boneIndex)native_invoker.push_arg_float(scale)native_invoker.push_arg_bool(xAxis)native_invoker.push_arg_bool(yAxis)native_invoker.push_arg_bool(zAxis)native_invoker.push_arg_float(r)native_invoker.push_arg_float(g)native_invoker.push_arg_float(b)native_invoker.push_arg_float(a)native_invoker.end_call_2(0xDDE23F30CC5A0F03)return native_invoker.get_return_value_int()end
NETWORK_FADE_IN_ENTITY=--[[void]] function(--[[Entity (int)]] entity,--[[BOOL (bool)]] state)native_invoker.begin_call()native_invoker.push_arg_int(entity)native_invoker.push_arg_bool(state)native_invoker.end_call_2(0x1F4ED342ACEFE62D)end
SPECIAL_ABILITY_FILL_METER=--[[void]] function(--[[Player (int)]] player,--[[BOOL (bool)]] p1)native_invoker.begin_call()native_invoker.push_arg_int(player)native_invoker.push_arg_bool(p1)native_invoker.end_call_2(0x3DACA8DDC6FD4980)end
SHOOT_SINGLE_BULLET_BETWEEN_COORDS_IGNORE_ENTITY=--[[void]] function(--[[float]] x1,--[[float]] y1,--[[float]] z1,--[[float]] x2,--[[float]] y2,--[[float]] z2,--[[int]] damage,--[[BOOL (bool)]] p7,--[[Hash (int)]] weaponHash,--[[Ped (int)]] ownerPed,--[[BOOL (bool)]] isAudible,--[[BOOL (bool)]] isInvisible,--[[float]] speed,--[[Entity (int)]] entity)native_invoker.begin_call()native_invoker.push_arg_float(x1)native_invoker.push_arg_float(y1)native_invoker.push_arg_float(z1)native_invoker.push_arg_float(x2)native_invoker.push_arg_float(y2)native_invoker.push_arg_float(z2)native_invoker.push_arg_int(damage)native_invoker.push_arg_bool(p7)native_invoker.push_arg_int(weaponHash)native_invoker.push_arg_int(ownerPed)native_invoker.push_arg_bool(isAudible)native_invoker.push_arg_bool(isInvisible)native_invoker.push_arg_float(speed)native_invoker.push_arg_int(entity)native_invoker.end_call_2(0xE3A7742E0B7A2F8B)end
PLAY_SOUND_FROM_ENTITY=--[[void]] function(--[[int]] soundId,--[[string]] audioName,--[[Entity (int)]] entity,--[[string]] audioRef,--[[BOOL (bool)]] isNetwork)native_invoker.begin_call()native_invoker.push_arg_int(soundId)native_invoker.push_arg_string(audioName)native_invoker.push_arg_int(entity)native_invoker.push_arg_string(audioRef)native_invoker.push_arg_bool(isNetwork)native_invoker.end_call_2(0xE65F427EB70AB1ED)end
DOES_ENTITY_EXIST=--[[BOOL (bool)]] function(--[[Entity (int)]] entity)native_invoker.begin_call()native_invoker.push_arg_int(entity)native_invoker.end_call_2(0x7239B21A38F536BA)end
GET_CURRENT_PED_WEAPON_ENTITY_INDEX=--[[Entity (int)]] function(--[[Ped (int)]] ped)native_invoker.begin_call()native_invoker.push_arg_int(ped)native_invoker.end_call_2(0x3B390A939AF0B5FC)return native_invoker.get_return_value_int()end
GET_ENTITY_BONE_INDEX_BY_NAME=--[[int]] function(--[[Entity (int)]] entity,--[[string]] boneName)native_invoker.begin_call()native_invoker.push_arg_int(entity)native_invoker.push_arg_string(boneName)native_invoker.end_call_2(0xFB71170B7E76ACBA)return native_invoker.get_return_value_int()end
CLEAR_AREA_OF_VEHICLES=--[[void]] function(--[[float]] x,--[[float]] y,--[[float]] z,--[[float]] radius,--[[BOOL (bool)]] p4,--[[BOOL (bool)]] p5,--[[BOOL (bool)]] p6,--[[BOOL (bool)]] p7,--[[BOOL (bool)]] p8,--[[BOOL (bool)]] p9)native_invoker.begin_call()native_invoker.push_arg_float(x)native_invoker.push_arg_float(y)native_invoker.push_arg_float(z)native_invoker.push_arg_float(radius)native_invoker.push_arg_bool(p4)native_invoker.push_arg_bool(p5)native_invoker.push_arg_bool(p6)native_invoker.push_arg_bool(p7)native_invoker.push_arg_bool(p8)native_invoker.push_arg_bool(p9)native_invoker.end_call_2(0x01C7B9B38428AEB6)end
SET_ENTITY_HEALTH=--[[void]] function(--[[Entity (int)]] entity,--[[int]] health)native_invoker.begin_call()native_invoker.push_arg_int(entity)native_invoker.push_arg_int(health)native_invoker.end_call_2(0x6B76DC1F3AE6E6A3)end
GET_PED_IN_VEHICLE_SEAT=--[[Ped (int)]] function(--[[Vehicle (int)]] vehicle,--[[int]] seatIndex)native_invoker.begin_call()native_invoker.push_arg_int(vehicle)native_invoker.push_arg_int(seatIndex)native_invoker.end_call_2(0xBB40DD2270B65366)return native_invoker.get_return_value_int()end
GET_ENTITY_COORDS=--[[Vector3 (vector3)]] function(--[[Entity (int)]] entity)native_invoker.begin_call()native_invoker.push_arg_int(entity)native_invoker.end_call_2(0x3FEF770D40960D5A)return native_invoker.get_return_value_vector3()end
NETWORK_EXPLODE_VEHICLE=--[[BOOL (bool)]] function(--[[Vehicle (int)]] vehicle,--[[BOOL (bool)]] isAudible,--[[BOOL (bool)]] isInvisible)native_invoker.begin_call()native_invoker.push_arg_int(vehicle)native_invoker.push_arg_bool(isAudible)native_invoker.push_arg_bool(isInvisible)native_invoker.end_call_2(0x301A42153C9AD707)return native_invoker.get_return_value_bool()end
REMOVE_ALL_STICKY_BOMBS_FROM_ENTITY=--[[void]] function(--[[Entity (int)]] entity)native_invoker.begin_call()native_invoker.push_arg_int(entity)native_invoker.end_call_2(0x715135F4B82AC90D)end